### ISSUE TITLE
Using the getAPI call

### ISSUE THREAD

**Issue by bradrice** [chintan9/plyr-react#727]
Is this the proper location for adding an eventlistener?

```
const getAPI = (plyr: PlyrJS | null) => {
  // if (!plyr)
  //   return () =>
  //     new Proxy(
  //       { plyr: { source: null } },
  //       {
  //         get: (target, prop) => {
  //           if (prop === 'plyr') {
  //             return target[prop]
  //           }
  //           return noop
  //         }
  //       }
  //     )
// add EventListeners here
    plyr.on('play', (e)=>{console.log("playing", e)});

  return () => ({
    /**
     * Plyr instance with all of its functionality
     */
    plyr
  })
}
```
I'm getting errors:

```
Uncaught TypeError: Cannot read properties of null (reading 'on')
    at getAPI (audioplayer.tsx:53:1)
    at useAptor.js:24:1
    at mountMemo (react-dom.development.js:15846:1)
    at Object.useMemo (react-dom.development.js:16219:1)
    at useMemo (react.development.js:1532:1)
    at useAptor (useAptor.js:24:1)
    at audioplayer.tsx:66:1
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateForwardRef (react-dom.development.js:17044:1)
    at beginWork (react-dom.development.js:19098:1)
getAPI @ audioplayer.tsx:53
(anonymous) @ useAptor.js:24
mountMemo @ react-dom.development.js:15846
useMemo @ react-dom.development.js:16219
useMemo @ react.development.js:1532
useAptor @ useAptor.js:24
(anonymous) @ audioplayer.tsx:66
renderWithHooks @ react-dom.development.js:14985
updateForwardRef @ react-dom.development.js:17044
beginWork @ react-dom.development.js:19098
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
./src/index.tsx @ index.tsx:7
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
react-dom.development.js:20085 The above error occurred in the <Plyr> component:

    at http://localhost:3000/static/js/bundle.js:175:5
    at div
    at App
```

**Comment by bradrice** [comment]
I'm finding use of the raptorRef in useEffect is working for adding eventlisteners.

```
useEffect(()=> {
    raptorRef.current.plyr.on('play', ()=>{
      console.log("playing");
    })
    raptorRef.current.plyr.on('ended', ()=> {
      console.log("ended");
    });
    raptorRef.current.plyr.muted = true;
  })
```

**Comment by amirHossein-Ebrahimi** [comment]
Good to hear that, I will do the package part in a few days.
So you can install the alpha version from the git (with less code and a faster-installing process)

I'm going to close the issue, in case you found any other issue, reopen this issue, or simply create a new one. or you can ask in [the discussion section
](https://github.com/chintan9/plyr-react/discussions)
