### ISSUE TITLE
Writing jest test throws a TypeError in component

### ISSUE THREAD

**Issue by bradrice** [chintan9/plyr-react#915]
**Describe the bug**
When I write a test to test my audio or video component I get errors. I'm able to set an ErrorBoundary in components that import the audio or video component, but testing the component directly is an issue.

**To Reproduce**
write a jest test on the compoenent

**Expected behavior**
A passing test

Error is: 
TypeError: 'toString' called on an object that is not a valid instance of Location.

A longer error is: 

```bash
console.error
    Error: Uncaught [TypeError: 'toString' called on an object that is not a valid instance of Location.]
        at reportException (C:\Users\brice\source\repos\nextplayer\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
        at innerInvokeEventListeners (C:\Users\brice\source\repos\nextplayer\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:341:9)
        at invokeEventListeners (C:\Users\brice\source\repos\nextplayer\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:274:3)
        at HTMLUnknownElementImpl._dispatch (C:\Users\brice\source\repos\nextplayer\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:221:9)
        at HTMLUnknownElementImpl.dispatchEvent (C:\Users\brice\source\repos\nextplayer\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:94:17)
        at HTMLUnknownElement.dispatchEvent (C:\Users\brice\source\repos\nextplayer\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:231:34)
        at Object.invokeGuardedCallbackDev (C:\Users\brice\source\repos\nextplayer\node_modules\react-dom\cjs\react-dom.development.js:3994:16)
        at invokeGuardedCallback (C:\Users\brice\source\repos\nextplayer\node_modules\react-dom\cjs\react-dom.development.js:4056:31)
        at flushPassiveEffectsImpl (C:\Users\brice\source\repos\nextplayer\node_modules\react-dom\cjs\react-dom.development.js:23574:9)
        at unstable_runWithPriority (C:\Users\brice\source\repos\nextplayer\node_modules\scheduler\cjs\scheduler.development.js:468:12) TypeError: 'toString' called on an object that is not a valid instance of Location.
        at Object.toString (C:\Users\brice\source\repos\nextplayer\node_modules\jsdom\lib\jsdom\living\generated\Location.js:126:17)
        at String (<anonymous>)
        at Object.exports.DOMString (C:\Users\brice\source\repos\nextplayer\node_modules\webidl-conversions\lib\index.js:283:12)
        at Object.exports.USVString (C:\Users\brice\source\repos\nextplayer\node_modules\webidl-conversions\lib\index.js:299:23)
        at new URL (C:\Users\brice\source\repos\nextplayer\node_modules\whatwg-url\dist\URL.js:103:44)
        at Plyr.getIconUrl (C:\Users\brice\source\repos\nextplayer\node_modules\plyr\dist\plyr.js:1458:19)
        at Plyr.inject (C:\Users\brice\source\repos\nextplayer\node_modules\plyr\dist\plyr.js:2808:42)
        at Plyr.build (C:\Users\brice\source\repos\nextplayer\node_modules\plyr\dist\plyr.js:4165:25)
        at new Plyr (C:\Users\brice\source\repos\nextplayer\node_modules\plyr\dist\plyr.js:8021:18)
        at instantiate (C:\Users\brice\source\repos\nextplayer\node_modules\plyr-react\index.js:70:14)

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
```

**Comment by realamirhe** [comment]
> I'm able to set an ErrorBoundary in components that import the audio or video component, but testing the component directly is an issue.

I guess that's because, renderer will render shallowly one level by default.

Did you try to mock plyr for your jest?
could you provide your test and jest setup?

for more information could you check our jest 
[Plyr.test.tsx](https://github.com/chintan9/plyr-react/blob/master/tests/Plyr.test.tsx#L6)

**Comment by bradrice** [comment]
As always, Emir, you are a big help to me. That was the solution.
